# Vector and Matrix Transpose
This document will cover:
- Transposing vectors and Matrices

In [14]:
# Transposing a Vector with PyTorch
import torch
vector = torch.Tensor([[1,2,3,4,5,6,7,8,9,0]])
print(vector)
print(vector.T)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9., 0.]])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.],
        [0.]])


In [13]:
# Transposing a Matrix with PyTorch
import torch
matrix = torch.Tensor([
    [12, 3,12,2,78],
    [3,12,41,2,78],
    [12, 3,12,2,78]
    ])
print(matrix)
print(matrix.T) # the .T method will Transpose the matrix

tensor([[12.,  3., 12.,  2., 78.],
        [ 3., 12., 41.,  2., 78.],
        [12.,  3., 12.,  2., 78.]])
tensor([[12.,  3., 12.],
        [ 3., 12.,  3.],
        [12., 41., 12.],
        [ 2.,  2.,  2.],
        [78., 78., 78.]])
