#### Import Numpy Libraries

In [102]:
import numpy as np

#### Basic Python List and Numpy Array

In [103]:
# Python List
mylist = [1,2,3,4,5,6,7]
print(f'Python List: {mylist}')

# Numpy Array
arr = np.array(mylist)
print(f'Numpy Array: {arr}')

Python List: [1, 2, 3, 4, 5, 6, 7]
Numpy Array: [1 2 3 4 5 6 7]


#### Nested Python List and Numpy Array

In [104]:
# Nested Python List
mylist = [[1,2,3], [4,5,6], [7,8,9]]
print(f'Nested Python List: {mylist}')
# Nested Numpy Array
arr = np.array(mylist)
print(f'Nested Numpy Array: {arr}')

Nested Python List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Nested Numpy Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Numpy Arange

In [105]:
start = 0 # Inclusive Start
stop = 10 # Non-Inclusive Stop
step = 1

print(np.arange(start, stop, step))
print(np.arange(0,10,1))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Numpy Zeros Function

In [106]:
xinput = 10
yinput = 4
print(f'Zeros ex1: {np.zeros(xinput)}')
print(f'Zeros ex2: {np.zeros((yinput, xinput))}')

Zeros ex1: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Zeros ex2: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Numpy Ones Function

In [107]:
xinput = 2
yinput = 4

print(np.ones(xinput))                          # Normal 1d
print(f'\n {np.ones((yinput, xinput))}')        # Normal 2d
print(f'\n {np.ones((yinput, xinput))+3}')      # Addition
print(f'\n {np.ones((yinput, xinput))*20}')     # Multilplication
print(f'\n {np.ones((yinput, xinput))-10}')     # Subtraction
print(f'\n {np.ones((yinput, xinput))/2}')      # Division

[1. 1.]

 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 [[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]

 [[20. 20.]
 [20. 20.]
 [20. 20.]
 [20. 20.]]

 [[-9. -9.]
 [-9. -9.]
 [-9. -9.]
 [-9. -9.]]

 [[0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]]


#### Numpy Linspace

In [108]:
start = 0   # Inclusive Start
stop = 92   # Inclusive Stop
nitems = 5
np.linspace(start, stop, nitems)

# Will return an array of 5 evenly spaced numbers between 0 and 92

array([ 0., 23., 46., 69., 92.])

#### Numpy Identity Matrix

In [109]:
np.eye(5)
# Will print a 5x5 array of numbers with ones going across the diagonal (top-left to bottom-right)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Numpy Random Numbers

In [113]:
np.random.rand(2, 2)    # random numbers between 0 and 1
np.random.randn(2,2)    # random numbers between -1 and 1
np.random.normal(22, 10, (2,2))     # (Mean, Standard Deviation, Size)
np.random.randint(0, 20, (2, 2))    # (Min, Max, Size)

array([[ 7,  5],
       [18, 18]])

##### Numpy Random Seed

In [119]:
np.random.seed(42)  # Seed 42 will always return the values shown
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

#### argmin(), argmax(), max(), min()

In [126]:
ranarr = np.random.randint(0, 200, 5)
print(ranarr)           # Returns Values in ranarr
print(ranarr.max())     # Returns Highest number in ranarr
print(ranarr.min())     # Returns Lowest number in ranarr
print(ranarr.argmax())  # Returns the index of the Highest number in ranarr
print(ranarr.argmin())  # Returns the index of the lowest number in ranarr

[ 99 103 151 130 149]
151
99
2
0


#### Numpy DType

In [128]:
ranarr.dtype    # Returns the datatype of a variable

dtype('int32')

: 