In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Indexing

In [8]:
start = 2   # Inclusive Start
stop = 6   # Non-inclusive Stop
index = 8   # Index Position
print(arr[index])
print(arr[start:stop])

print(arr[:stop])   # Prints from the beginning to index 5
print(arr[start:])  # Prints from index 2 to the end

8
[2 3 4 5]
[0 1 2 3 4 5]
[ 2  3  4  5  6  7  8  9 10]


#### Slicing Array

In [13]:
arr = np.random.randint(0, 100, 6)
arr_slice = arr[:2]
print(arr)
print(arr_slice)
arr_slice[:] = 99
print(arr_slice)
print(arr)
# Changing the values of a slice of an array will directly affect the original array

[72 95 61 52 98 81]
[72 95]
[99 99]
[99 99 61 52 98 81]


: 