# The Perceptron and ANN Architecture
This document will cover:
- The basic architecture of an ANN (Artificial Neural Networks)
- The linear and nonlinear components of an artificial neural network
- Several key terms of neural networks

### Linear vs Non-Linear Operations
- Linear: Addition and Scalar-Multiplications
- Nonlinear: Anything Else

|Linear|Non-Linear|
|:--|:--|
|Linear Models only solve Linearly seperable problems|Nonlinear models can solve more complex problems|
|Never use a Linear model for a Non-linear problem|Never use a Nonlinear model for a Linear problem|

#### The math of deep learning

In [70]:
import torch
x = torch.randn(3, 2); w = torch.tensor([[.05, .293, .2726], [.095, .23, .226]]);
print(x)
print(w)
print('\nTransposed: ')
print(x.T)
print(w)

yHat = torch.sigmoid(x.T*w)
print('\n\n', yHat)

tensor([[ 0.9644,  0.7475],
        [-1.3358,  1.1041],
        [ 1.1615,  0.1067]])
tensor([[0.0500, 0.2930, 0.2726],
        [0.0950, 0.2300, 0.2260]])

Transposed: 
tensor([[ 0.9644, -1.3358,  1.1615],
        [ 0.7475,  1.1041,  0.1067]])
tensor([[0.0500, 0.2930, 0.2726],
        [0.0950, 0.2300, 0.2260]])


 tensor([[0.5121, 0.4034, 0.5785],
        [0.5177, 0.5631, 0.5060]])
