# The Perceptron and ANN Architecture
This document will cover:
- The basic architecture of an ANN (Artificial Neural Networks)
- The linear and nonlinear components of an artificial neural network
- Several key terms of neural networks

### Linear vs Non-Linear Operations
- Linear: Addition and Scalar-Multiplications
- Nonlinear: Anything Else

|Linear|Non-Linear|
|:--|:--|
|Linear Models only solve Linearly seperable problems|Nonlinear models can solve more complex problems|
|Never use a Linear model for a Non-linear problem|Never use a Nonlinear model for a Linear problem|

#### The math of deep learning

In [132]:
import torch
x = torch.randn(3, 2); w = torch.tensor([[.05, .293, .2726], [.095, .23, .226]]);
print(x)
print(w)
print('\nTransposed: ')
print(x.T)
print(w)

yHat = torch.mm(x, w)

print('\n\n',yHat)
print(torch.sigmoid(yHat))

tensor([[1.5388, 0.1232],
        [1.5489, 0.1055],
        [0.3618, 1.0498]])
tensor([[0.0500, 0.2930, 0.2726],
        [0.0950, 0.2300, 0.2260]])

Transposed: 
tensor([[1.5388, 1.5489, 0.3618],
        [0.1232, 0.1055, 1.0498]])
tensor([[0.0500, 0.2930, 0.2726],
        [0.0950, 0.2300, 0.2260]])


 tensor([[0.0886, 0.4792, 0.4473],
        [0.0875, 0.4781, 0.4461],
        [0.1178, 0.3475, 0.3359]])
tensor([[0.5221, 0.6176, 0.6100],
        [0.5219, 0.6173, 0.6097],
        [0.5294, 0.5860, 0.5832]])
